# Generated by Django 2.2.3 on 2019-07-03 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='authuserlog',
            table='auth_user_log',
        ),
    ]
