# Generated by Django 2.2.3 on 2019-07-03 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_data', '0002_auto_20190703_1600'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuthUserLog',
        ),
    ]
