# Generated by Django 2.2.3 on 2019-07-03 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_data', '0003_delete_authuserlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthUserLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('addtime', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'auth_user_log',
                'managed': True,
            },
        ),
    ]
