# Generated by Django 2.2.3 on 2019-07-03 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_data', '0004_authuserlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authuserlog',
            name='username',
            field=models.CharField(max_length=150),
        ),
    ]
