# Generated by Django 2.2.3 on 2019-07-03 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_data', '0005_auto_20190703_1719'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobname', models.CharField(max_length=150)),
                ('companyname', models.CharField(max_length=150)),
                ('jobadr', models.CharField(max_length=150)),
                ('ctype', models.CharField(max_length=150)),
                ('cscale', models.CharField(max_length=150)),
                ('cindustry', models.CharField(max_length=150)),
                ('csort', models.CharField(max_length=150)),
                ('number', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=254)),
            ],
            options={
                'db_table': 'employment',
                'managed': True,
            },
        ),
    ]
