# Generated by Django 2.2.3 on 2019-07-03 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_data', '0006_employment'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmploymentData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobname', models.CharField(max_length=50)),
                ('companyname', models.CharField(max_length=50)),
                ('jobadr', models.CharField(max_length=50)),
                ('releasetime', models.CharField(max_length=50)),
                ('ctype', models.CharField(max_length=50)),
                ('cscale', models.CharField(max_length=50)),
                ('cindustry', models.CharField(max_length=50)),
                ('csort', models.CharField(max_length=50)),
                ('number', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=254)),
            ],
            options={
                'db_table': 'employment_data',
                'managed': True,
            },
        ),
        migrations.DeleteModel(
            name='Employment',
        ),
    ]
