# Generated by Django 2.2.3 on 2019-07-03 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_data', '0007_auto_20190703_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employmentdata',
            name='cindustry',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='employmentdata',
            name='companyname',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='employmentdata',
            name='cscale',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='employmentdata',
            name='csort',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='employmentdata',
            name='ctype',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='employmentdata',
            name='jobadr',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='employmentdata',
            name='jobname',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='employmentdata',
            name='number',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='employmentdata',
            name='releasetime',
            field=models.CharField(max_length=254),
        ),
    ]
