# Generated by Django 2.2.4 on 2019-09-15 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddu_app', '0002_usertoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='StuInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_name', models.CharField(max_length=64)),
                ('stu_age', models.CharField(max_length=64)),
                ('sex', models.CharField(max_length=64)),
                ('stu_num', models.CharField(max_length=64)),
                ('phone', models.CharField(max_length=64)),
                ('college', models.CharField(max_length=64)),
                ('class_num', models.CharField(max_length=64)),
                ('major', models.CharField(max_length=64)),
                ('depart', models.CharField(max_length=64)),
                ('position', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'stu_info',
            },
        ),
    ]
