# Generated by Django 2.2.4 on 2019-10-16 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ddu_app', '0004_stusinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StusInfo',
        ),
    ]
