# Generated by Django 2.2.4 on 2019-10-16 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddu_app', '0005_delete_stusinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorsheadersCorsmodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cors', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'corsheaders_corsmodel',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_name', models.CharField(max_length=64)),
                ('stu_age', models.CharField(max_length=64)),
                ('sex', models.CharField(max_length=64)),
                ('stu_num', models.CharField(max_length=64)),
                ('phone', models.CharField(max_length=64)),
                ('college', models.CharField(max_length=64)),
                ('class_num', models.CharField(max_length=64)),
                ('major', models.CharField(max_length=64)),
                ('depart', models.CharField(max_length=64)),
                ('position', models.CharField(max_length=64)),
                ('stu_id', models.CharField(max_length=64)),
                ('nation', models.CharField(max_length=10)),
                ('stu_addr', models.CharField(max_length=64)),
                ('others', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'student_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StudentsInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_name', models.CharField(max_length=64)),
                ('stu_age', models.CharField(max_length=64)),
                ('sex', models.CharField(max_length=64)),
                ('stu_num', models.CharField(max_length=64)),
                ('phone', models.CharField(max_length=64)),
                ('college', models.CharField(max_length=64)),
                ('class_num', models.CharField(max_length=64)),
                ('major', models.CharField(max_length=64)),
                ('depart', models.CharField(max_length=64)),
                ('position', models.CharField(max_length=64)),
                ('stu_id', models.CharField(max_length=64)),
                ('nation', models.CharField(max_length=10)),
                ('stu_addr', models.CharField(max_length=64)),
                ('others', models.CharField(max_length=200)),
                ('stu_birth', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'students_info',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='stuinfo',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='userinfo',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='usertoken',
            options={'managed': False},
        ),
    ]
