# Generated by Django 2.2.3 on 2019-11-06 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MedicineInfo',
        ),
    ]
