# Generated by Django 2.2.3 on 2019-11-06 11:13

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_delete_medicineinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicineInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pmedid', models.CharField(max_length=50, verbose_name='编号')),
                ('Pmedname', models.CharField(max_length=50, verbose_name='药物名称')),
                ('Pchangjia', models.CharField(max_length=50, verbose_name='生产厂家')),
                ('Pdate', models.CharField(max_length=50, verbose_name='生产日期')),
                ('bzq', models.CharField(max_length=50, verbose_name='保质期')),
                ('using', models.CharField(max_length=50, verbose_name='用途')),
                ('size', models.CharField(max_length=50, verbose_name='规格')),
                ('inprice', models.CharField(max_length=50, verbose_name='进货价')),
                ('outprice', models.CharField(max_length=50, verbose_name='销售价')),
                ('stuffid', models.IntegerField(blank=True, null=True, verbose_name='员工编号')),
                ('userid', models.IntegerField(blank=True, null=True, verbose_name='客户编号')),
            ],
            options={
                'verbose_name': '药物信息',
                'verbose_name_plural': '药物信息',
            },
        ),
        migrations.CreateModel(
            name='UserToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255, verbose_name='密钥')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='hospital.LoginInfo')),
            ],
            options={
                'verbose_name': '药物信息',
                'verbose_name_plural': '药物信息',
            },
        ),
    ]
