# Generated by Django 2.2.3 on 2019-11-06 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0005_usertoken'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConditionInfo',
        ),
        migrations.DeleteModel(
            name='MedicineInfo',
        ),
        migrations.RemoveField(
            model_name='usertoken',
            name='user',
        ),
        migrations.DeleteModel(
            name='LoginInfo',
        ),
        migrations.DeleteModel(
            name='UserToken',
        ),
    ]
