# Generated by Django 2.2.3 on 2019-11-06 13:01

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0006_auto_20191106_1301'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConditionInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pname', models.CharField(blank=True, max_length=50, null=True, verbose_name='患者名字')),
                ('Psex', models.CharField(choices=[('girl', '女'), ('boy', '男')], default='girl', max_length=50, verbose_name='患者性别')),
                ('Page', models.IntegerField(verbose_name='患者年龄')),
                ('Phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='患者电话')),
                ('Psfz', models.CharField(blank=True, max_length=50, null=True, verbose_name='患者身份证')),
                ('Money', models.IntegerField(blank=True, null=True, verbose_name='医药费')),
                ('Adds', models.CharField(blank=True, max_length=200, null=True, verbose_name='患者地址')),
                ('blood', models.CharField(blank=True, max_length=50, null=True, verbose_name='患者血型')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('condition', models.CharField(max_length=50, verbose_name='患者病况')),
            ],
            options={
                'verbose_name': '病况信息',
                'verbose_name_plural': '病况信息',
            },
        ),
        migrations.CreateModel(
            name='LoginInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Uid', models.IntegerField(verbose_name='登录者ID')),
                ('Pwd', models.CharField(max_length=50, verbose_name='登录密码')),
                ('Uname', models.CharField(blank=True, max_length=50, null=True, verbose_name='姓名')),
                ('Sex', models.CharField(choices=[('girl', '女'), ('boy', '男'), ('unknown', '未知')], default='unknown', max_length=50, verbose_name='性别')),
                ('Age', models.IntegerField(verbose_name='年龄')),
                ('Identity', models.CharField(choices=[('registration', '挂号'), ('doctor', '医生')], default='registration', max_length=50, verbose_name='类型')),
                ('Office', models.CharField(blank=True, max_length=50, null=True, verbose_name='科室')),
                ('stata', models.IntegerField(blank=True, null=True)),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '登录信息',
                'verbose_name_plural': '登录信息',
            },
        ),
        migrations.CreateModel(
            name='MedicineInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pmedid', models.CharField(max_length=50, verbose_name='编号')),
                ('Pmedname', models.CharField(max_length=50, verbose_name='药物名称')),
                ('Pchangjia', models.CharField(max_length=50, verbose_name='生产厂家')),
                ('Pdate', models.CharField(max_length=50, verbose_name='生产日期')),
                ('bzq', models.CharField(max_length=50, verbose_name='保质期')),
                ('using', models.CharField(max_length=50, verbose_name='用途')),
                ('size', models.CharField(max_length=50, verbose_name='规格')),
                ('inprice', models.CharField(max_length=50, verbose_name='进货价')),
                ('outprice', models.CharField(max_length=50, verbose_name='销售价')),
                ('stuffid', models.IntegerField(blank=True, null=True, verbose_name='员工编号')),
                ('userid', models.IntegerField(blank=True, null=True, verbose_name='客户编号')),
            ],
            options={
                'verbose_name': '药物信息',
                'verbose_name_plural': '药物信息',
            },
        ),
        migrations.CreateModel(
            name='UserToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255, verbose_name='密钥')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('user_type', models.CharField(max_length=10, verbose_name='用户类型')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='hospital.LoginInfo')),
            ],
            options={
                'verbose_name': '药物信息',
                'verbose_name_plural': '药物信息',
            },
        ),
    ]
