# Generated by Django 2.2.3 on 2019-11-06 14:34

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0008_delete_usertoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255, verbose_name='密钥')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('user_type', models.CharField(max_length=50, verbose_name='用户类型')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='hospital.LoginInfo')),
            ],
            options={
                'verbose_name': '药物信息',
                'verbose_name_plural': '药物信息',
            },
        ),
    ]
