# Generated by Django 2.2.3 on 2019-11-09 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0009_usertoken'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConditionInfo',
        ),
    ]
