# Generated by Django 2.2.4 on 2019-10-16 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app02', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StuInfo',
        ),
        migrations.DeleteModel(
            name='UserInfo',
        ),
        migrations.DeleteModel(
            name='UserToken',
        ),
    ]
